### ISSUE TITLE
androidBestLocationTracker - will it do this?

### ISSUE THREAD

**Issue by russell-parrott** [balwinderSingh1989/androidBestLocationTracker#1]
Hi balwinderSingh1989, found androidBestLocationTracker via StackOverflow, it looks exactly like a simple app I need - downside, I do not know mobile development at all.  You say if a question ask / email - sorry cannot find your mail. So the question 'is' - is androidBestLocationTracker basically an app ready to go? if not what do I need to do? and/or can you help :) My need is very simple a tracking app (permissions granted) that fires a request to a Firebase database on location change.  Would be great/preferable if this could be done 'in the background' without the app actually being open.  Hopefully you still 'monitor' this git and I look forward to any reply - cheers

**Comment by balwinderSingh1989** [comment]
Hi Rusell,

This is not an app but a library that can be integrated directly with any android app to get best location updates.

To answer your requirement:

You would need to create a app that can make use of this library to fetch location updates and forward the same to Firebase in background using Workmanager/JobScheduler or foreground services.

You can share your requirement at er.vicky1989@gmail.com in case you want any assistance in development.

**Comment by balwinderSingh1989** [comment]
Closing
